# Generated by Django 4.0.1 on 2022-04-19 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_has_ball', models.BooleanField(default=False)),
                ('has_started', models.BooleanField(default=False)),
                ('is_over', models.BooleanField(default=False)),
                ('position', models.DecimalField(decimal_places=20, default=0, max_digits=30)),
                ('velocity_x', models.DecimalField(decimal_places=20, default=0, max_digits=30)),
                ('velocity_y', models.DecimalField(decimal_places=20, default=0, max_digits=30)),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='social_app.player')),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='social_app.player')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='social_app.player')),
            ],
            options={
                'unique_together': {('player', 'friend')},
            },
        ),
    ]
